Web/Work/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include("trends.urls")),
]

Web/Work/trends/urls.py
from django.urls import path
from . import views
app_name = 'trends'
urlpatterns = [
    path('keyword/', views.keyword, name="keyword"),
    path('keyword/<int:pk>/', views.keyword_detail, name="detail"),
    path('keyword/crawling/', views.crawling, name="crwaling"),
    path('keyword/crawling/histogram/', views.crawling_histogram, name="hist"),
    path('keyword/crawling/advanced/', views.crawling_advanced, name="adv_hist"),
]

Web/Work/trends/models.py
from django.db import models

# Create your models here.
class KeyWord(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)

class Trend(models.Model):
    name = models.TextField()
    result = models.IntegerField() 
    search_period = models.TextField()
    created_at = models.DateField(auto_now_add=True)

Web/Work/trends/forms.py
from django import forms
from . import models
class KeywordForm(forms.ModelForm):
    class Meta:
        model = models.KeyWord
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'placeholder': '키워드를 작성해 주세요.',
                    }
                )
        }

Web/Work/trends/views.py
from django.shortcuts import render, redirect
from .models import KeyWord as K
from .forms import KeywordForm
# Create your views here.
def keyword(request):

    if request.method == "POST":
        form = KeywordForm(request.POST)
        if form.is_valid():
            keyword = form.save()
        return redirect('trends:keyword')
    
    else:
        keywords = K.objects.all()
        form = KeywordForm()
        context = {
            'keywords' : keywords,
            'form' : form
        }
        return render(request, 'trends/keyword.html', context)

def keyword_detail(request, pk):
    if request.method == "POST":
        keyword = K.objects.get(pk = pk)
        keyword.delete()
    return redirect('trends:keyword')

def crawling(request):
    return render(request, 'trends/crawling.html')

def crawling_histogram(request):
    return render(request, 'trends/crawling_histogram.html')

def crawling_advanced(request):
    return render(request, 'trends/crawling_advanced.html')

Web/Work/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>트렌드 분석 애플리케이션</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <div class="m-3 p-3">
    <nav>
      <div>
        <h1 class="fw-bold mb-3">트렌드 분석 애플리케이션</h1>
      </div>
      <div class = "pt-1">
        <a href="{% url "trends:keyword" %}">키워드 추가</a> | 
        <a href="{% url "trends:crwaling" %}">크롤링</a> | 
        <a href="{% url "trends:hist" %}">히스토그램</a> | 
        <a href="{% url "trends:adv_hist" %}">지난 1년 크롤링</a> | 
      </div>
    </nav>
    <div class = "my-3 py-3">
      {% block content %}{% endblock content %}
    </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Web/Work/trends/templates/trends/crawling_advanced.html
{% extends "base.html" %}
{% block content %}
<h1>hello</h1>
{% endblock content %}

Web/Work/trends/templates/trends/crawling_hitsogram.html
{% extends "base.html" %}
{% block content %}
<h1>hello</h1>
{% endblock content %}

Web/Work/trends/templates/trends/crwaling.html
{% extends "base.html" %}
{% block content %}
<h1>hello</h1>
{% endblock content %}

Web/Work/trends/templates/trends/keyword.html
{% extends "base.html" %}
{% block content %}
<section>
    <h2 class ='fw-bold pb-3'> 키워드 추가</h2>
    
    <form action="{% url "trends:keyword" %}" method="POST">
        {% csrf_token %}
        {% comment %} {{form.as_p}} {% endcomment %}
        <p>키워드 : <input type="text" name="name" style="width:200px;"> 
        <input type="submit" value="생성하기"></p>
    </form>
    <hr>

    <h3 class = 'my-3 py-3'>◾ 분석을 원하는 키워드 목록</h3>
    {% for keyword in keywords %}

    <p clas = "fs-5">{{keyword.pk}}번째 키워드 - {{keyword.name}}</p>
    <form action="{% url "trends:detail" keyword.pk %}" method = "POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기">
    </form>
    <hr>

    {% empty %}
    <p class="fs-5">❗ 아직 등록된 키워드가 없습니다.</p>

    {% endfor %}
</section>
{% endblock content %}